### ISSUE TITLE
Expose API To Obj-C

### ISSUE THREAD

**Issue by burkeholland** [Yalantis/StarWars.iOS#3]
Any chance you could add the necessary decorations to expose this lib to Obj-C? That would allow us to create a plugin for this module for github.com/nativescript.

**Comment by burkeholland** [comment]
I did try and do this in a pull request, but I don't understand enough about Swift 2 to make the appropriate class changes

**Comment by serejahh** [comment]
Hi @burkeholland!

For now we don't have plans to be compatible with objective-c. If you want, you can create a pull request 😉 
Thanks!
