### ISSUE TITLE
Content length exceded for GIF

### ISSUE THREAD

**Issue by lfarah** [Yalantis/StarWars.iOS#5]
https://camo.githubusercontent.com/012ac6305c18bc9484d859343d027d3edb762669/68747470733a2f2f79616c616e7469732d636f6d2e73332e616d617a6f6e6177732e636f6d2f75706c6f6164732f636b656469746f722f70696374757265732f34392f636f6e74656e745f737461725f776172732d73686f745f5f315f2e676966

**Comment by serejahh** [comment]
Thanks for reporting the issue. I've update the preview
