### ISSUE TITLE
request for opengl objc animation code

### ISSUE THREAD

**Issue by lechium** [Yalantis/StarWars.iOS#7]
i read the blog that accompanied this repo about how this animation was created. i saw you originally wrote opengl one it in objc. is there any chance you have that code still and are willing to share it? i love this transition but am not going to use any swift in my current project and plan on trying to rewrite this in objc so it would speed things up tremendously for me. 

sorry if this isnt appropriate avenue to ask. didnt see a comment section on the blog:

**Comment by serejahh** [comment]
@artemSydorenko

**Comment by artemSydorenko** [comment]
no, sorry. I checked and seems I lost obj-c version.

**Comment by fresh83** [comment]
:/
